
[Source](https://customer.asianefficiency.com/omnifocus-premium-posts/section-5-rituals/post-5-1-morning-evening-rituals/ "Permalink to Post 5.1: Morning and Evening Rituals")

# Post 5.1: Morning and Evening Rituals

## Navigation

1. Introduction
2. Setting Up Morning and Evening Rituals
3. Accessing and Using Morning and Evening Rituals

* * *

## 1\. Introduction

Morning rituals are the specific steps that you take from the time that you wake up, to the time when you're ready to go to work.

Evening rituals are the flip-side of morning rituals, being the specific steps that you take when you're done with your day and winding down towards sleep.

Both rituals are preset scripts of winning moves that are all about energy management. Morning rituals are for getting you from perhaps a foggy, early-morning start to alert, productive and ready to deliver your most important tasks. Evening rituals are for helping you fall asleep easily and effortlessly.

Over time, we've come to recognize that there is more to productivity and task management beyond just completing the next action—the state, mood and how well-rested you are matters **a lot** as well.

The great thing about both morning and evening rituals is that they have a cumulative effect—the more you do them, the easier they become, and the more powerful that they become.

You'll see the basics of morning and evening rituals presented through examples in this post, but what we really want to get into is how to set up and implement them inside OmniFocus 2.

_**Note:** If you want to get into the details of morning or evening rituals, please see the [Asian Efficiency Primer][1]._
* * *

## 2\. Setting Up Morning and Evening Rituals

Setting up morning and evening rituals inside OmniFocus 2 isn't complicated at all.

Here's how it looks sequentially:

1. Create a top-level folder called "Rituals" in project view.
2. Create a single-action list within that folder called "Morning Ritual."
3. Create a second single-action list within that folder called "Evening Ritual."
4. Adjust the settings (see below).
5. Input your morning or evening ritual steps as actions.

_**Note:** You can name your folder or single-action list something else if you like, but we recommend "Rituals," "Morning Ritual," and "Evening Ritual" for simplicity._

Let's look at this visually.

**1\. Create a top-level folder called "Rituals" in project view.**

![Rituals Folder][2]

**2\. Create a single-action list within than folder called "Morning Ritual".**

![Morning Ritual SAL][3]

**3\. Create a single-action list within than folder called "Evening Ritual".**

![Evening Ritual SAL][4]

**4\. Adjust the settings.**

Here are the settings that you want to use for both single-action lists:

![Morning Evening Ritual Settings][5]

Of particular note are:

* Set the entire list to the context of _@Rituals_ (create this context if you need to).
* Do check, "Complete when completing last action."
* Set the defer and due dates to today—you can do this by going to that field and typing in "tod" or "today."
* Set the list to repeat every 1 day.
* (Optional) If you want your morning ritual steps to show up in your Execution/Today perspectives, flag the entire list.

**5\. Input your morning and evening ritual steps as actions.**

The last step is to type in your morning and evening ritual steps.

Here's what a bare-basics morning ritual can look like in OmniFocus 2:

![Morning Ritual Actions][6]

And here's what a bare-basics evening ritual can look like in OmniFocus 2:

![Evening Ritual Actions][7]

* * *

## 3\. Accessing and Using Morning and Evening Rituals

Once you have your morning and evening rituals set up inside OmniFocus 2, you can start using them immediately.

There are two places you will usually access your rituals—on the desktop, and on mobile (iPhone).

On the desktop you can simply navigate to projects view and then the morning or evening ritual single-action list within your rituals folder.

![Accessing Morning Evening Rituals][8]

On the iPhone, you can tap on projects, then rituals, then the morning or evening ritual single-action list.

![Accessing Morning Evening Rituals on iPhone][9]

What this looks like in real life, is waking up in the morning, reaching for your phone (which everyone does), launching OmniFocus, opening up the morning ritual list, and then starting at the first item and checking things off as they're done.

In the evening, it is about pulling up the evening ritual single-action list on your phone as you realize you're done for the day, and looking at the first item, actioning it, and then checking items off until you're ready to go to sleep.

Notice how we don't suggest using&nbsp;the forecast feature to check off our rituals. If you discover that you do prefer&nbsp;to use the forecast feature for this, you may&nbsp;notice that the view gets cluttered with all your ritual actions. To minimize that as much as possible, we would advise you to set very small windows of time for your defer and due dates, e.g., your morning rituals have a defer date might be at 5:00 AM and the due date is at 7:00 AM (2 hour window).

#### A Note About Contexts

You may have noticed that we have not recommended creating a custom perspective for your morning or evening rituals. The reason for this, is that context-based views don't let you use action groups (which we'll cover with regards to rituals [in the next post][10]), and because project-based views (which do let you use action groups) aren't accessible on the iPhone app. Regardless, the current setup of 3 taps to access your rituals is straightforward enough for everyday use.



[1]: https://customer.asianefficiency.com/primer/
[2]: https://customer.asianefficiency.com/wp-content/uploads/rituals-folder.jpg
[3]: https://customer.asianefficiency.com/wp-content/uploads/morning-ritual-sal.jpg
[4]: https://customer.asianefficiency.com/wp-content/uploads/evening-ritual-sal.jpg
[5]: https://customer.asianefficiency.com/wp-content/uploads/morning-evening-ritual-settings.jpg
[6]: https://customer.asianefficiency.com/wp-content/uploads/morning-ritual-actions.jpg
[7]: https://customer.asianefficiency.com/wp-content/uploads/evening-ritual-actions.jpg
[8]: https://customer.asianefficiency.com/wp-content/uploads/access-morning-evening-rituals.jpg
[9]: https://customer.asianefficiency.com/wp-content/uploads/access-morning-evening-rituals-iphone.jpg
[10]: https://customer.asianefficiency.com/omnifocus-premium-posts/section-5-rituals/post-5-2-advanced-daily-rituals/ "Post 5.2: Advanced Daily Rituals"
[11]: https://customer.asianefficiency.com/omnifocus-premium-posts/section-5-rituals/ "Section 5: Rituals"
[12]: https://customer.asianefficiency.com/omnifocus-premium-posts/
  